apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-maintenance
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictive-maintenance
  template:
    metadata:
      labels:
        app: predictive-maintenance
    spec:
      containers:
      - name: predictive-maintenance
        image: your-dockerhub-username/predictive-maintenance:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP
          value: "kafka-cluster-kafka-bootstrap.kafka:9092"
        - name: INPUT_TOPIC
          value: "telemetry-raw"
        - name: ALERT_TOPIC
          value: "maintenance-alerts"
        - name: ONOS_URL
          value: "http://onos-service.micro-onos.svc.cluster.local:8181/onos/v1"
        - name: MODEL_PATH
          value: "/models/autoencoder_model.h5"
        - name: ERROR_THRESHOLD
          value: "0.389"
        - name: HTTP_PORT
          value: "5001"
        - name: SWITCH_ID
          value: "of:0000000000000001"
        volumeMounts:
        - name: model-volume
          mountPath: /models
      volumes:
      - name: model-volume
        configMap:
          name: maintenance-model-config
---
apiVersion: v1
kind: Service
metadata:
  name: predictive-maintenance-service
  namespace: microservices
spec:
  selector:
    app: predictive-maintenance
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP