apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-maintenance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictive-maintenance
  template:
    metadata:
      labels:
        app: predictive-maintenance
    spec:
      containers:
      - name: predictive-maintenance
        image: your-dockerhub-username/predictive-maintenance:latest
        ports:
        - containerPort: 5001
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: MODEL_PATH
          value: "/app/autoencoder_model.h5"
---
apiVersion: v1
kind: Service
metadata:
  name: predictive-maintenance-service
spec:
  selector:
    app: predictive-maintenance
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

# kubectl apply -f predictive_maintenance_deployment.yaml