apiVersion: apps/v1
kind: Deployment
metadata:
  name: onos-controller
  namespace: micro-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onos
  template:
    metadata:
      labels:
        app: onos
    spec:
      nodeSelector:
        kubernetes.io/hostname: cloudnode
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: onos
        image: henok28/onos-diam:v3  # ✅ Make sure this is your latest push
        ports:
        - containerPort: 8181   # REST GUI
        - containerPort: 8101   # CLI SSH
        - containerPort: 6653   # OpenFlow
        - containerPort: 6633   # Legacy OF
        env:
        - name: ONOS_APPS
          value: openflow,gui
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: onos-service
  namespace: micro-onos
spec:
  selector:
    app: onos
  type: NodePort
  ports:
    - name: rest
      port: 8181
      targetPort: 8181
      nodePort: 30181
    - name: openflow
      port: 6653
      targetPort: 6653
      nodePort: 30653


# docker pull onosproject/onos
# kubectl apply -f onos_deployment.yaml
# Access ONOS UI from host: http://<NODE-IP>:30181/onos/ui : uname- onos and pass- rocks
# Then use REST APIs to install flows and Connect OVS switches to ONOS at tcp://<NODE-IP>:6653.