apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: security-enforcement-agent
  namespace: edge-agents
spec:
  selector:
    matchLabels:
      app: security-agent
  template:
    metadata:
      labels:
        app: security-agent
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        edge.kubeedge.io/exclude-cni: "true"
      initContainers:       # ✅ Add veth creation here
      - name: veth-setup
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            ip link add veth-br-sec type veth peer name veth-sec || true
            ip link set veth-br-sec up
            ip link set veth-sec up
            ovs-vsctl add-port br0 veth-br-sec || true
        securityContext:
          privileged: true
        volumeMounts:
          - name: dev-mount
            mountPath: /dev
          - name: ovsdb-socket
            mountPath: /var/run/openvswitch
      containers:
      - name: enforcement-agent
        image: henok28/security-enforcement-agent:v1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: ONOS_URL
          value: "http://192.168.56.121:8181"
        - name: OVS_BRIDGE
          value: "br0"
        - name: ENFORCE_MODE
          value: "onos"
        ports:
        - name: prom-metrics
          containerPort: 9000
        - name: flow-api
          containerPort: 5005
        volumeMounts:
        - name: dev-mount
          mountPath: /dev
        - name: ovsdb-socket
          mountPath: /var/run/openvswitch
      volumes:
      - name: dev-mount
        hostPath:
          path: /dev
      - name: ovsdb-socket
        hostPath:
          path: /var/run/openvswitch
