apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-manager
  template:
    metadata:
      labels:
        app: policy-manager
    spec:
      containers:
      - name: policy-manager
        image: your-dockerhub-username/policy-manager:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: policy-manager-service
spec:
  selector:
    app: policy-manager
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

# kubectl apply -f policy_manager_deployment.yaml