apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: test-app
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls

# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaTopic
# metadata:
#   name: telemetry-test
#   namespace: kafka
#   labels:
#     strimzi.io/cluster: kafka-cluster
# spec:
#   partitions: 3
#   replicas: 1
# ---
# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaUser
# metadata:
#   name: test-app
#   namespace: kafka
#   labels:
#     strimzi.io/cluster: kafka-cluster
# spec:
#   authentication:
#     type: tls
#   authorization:
#     type: simple
#     acls:
#       - resource:
#           type: topic
#           name: telemetry-test
#           patternType: literal
#         operations: ["Read","Write","Describe"]